# Compile Iconvert

options=SHOWFNAME
compiler=evo

all:					Iconvert

debug:        options = DEBUG SHOWFNAME
debug:				Iconvert

Iconvert:  			Iconvert.e
							$(compiler) Iconvert $(options)
clean:  			
							-delete Iconvert
