  OPT MODULE
  OPT EXPORT
  OPT PREPROCESS

CONST OTERR_FAILURE=-1,
      OTERR_SUCCESS=0,
      OTERR_BADTAG=1,
      OTERR_UNKNOWNTAG=2,
      OTERR_BADDATA=3,
      OTERR_NOMEMORY=4,
      OTERR_NOFACE=5,
      OTERR_BADFACE=6,
      OTERR_NOGLYPH=7,
      OTERR_BADGLYPH=8,
      OTERR_NOSHEAR=9,
      OTERR_NOROTATE=10,
      OTERR_TOOSMALL=11,
      OTERR_UNKNOWNGLYPH=12

