# Compile Pragma2Module

options=SHOWFNAME
compiler=evo

all:					Pragma2Module

debug:        options = DEBUG SHOWFNAME
debug:				Pragma2Module

Pragma2Module:		Pragma2Module.e
							$(compiler) Pragma2Module $(options)
clean:  			
							-delete Pragma2Module
