OPT MODULE
OPT EXPORT

CONST BATTMEM_SHARED_AMNESIA_ADDR=$40,
      BATTMEM_SHARED_AMNESIA_LEN=1,
      BATTMEM_SCSI_HOST_ID_ADDR=$41,
      BATTMEM_SCSI_HOST_ID_LEN=3,
      BATTMEM_SCSI_SYNC_XFER_ADDR=$44,
      BATTMEM_SCSI_SYNC_XFER_LEN=1,
      BATTMEM_SCSI_FAST_SYNC_ADDR=$45,
      BATTMEM_SCSI_FAST_SYNC_LEN=1,
      BATTMEM_SCSI_TAG_QUEUES_ADDR=$46,
      BATTMEM_SCSI_TAG_QUEUES_LEN=1

