OPT MODULE
OPT EXPORT

CONST BATTMEM_AMIGA_AMNESIA_ADDR=0,
      BATTMEM_AMIGA_AMNESIA_LEN=1,
      BATTMEM_SCSI_TIMEOUT_ADDR=1,
      BATTMEM_SCSI_TIMEOUT_LEN=1,
      BATTMEM_SCSI_LUNS_ADDR=2,
      BATTMEM_SCSI_LUNS_LEN=1

