OPT MODULE
OPT EXPORT

OPT PREPROCESS

CONST MR_SERIALPORT=0,
      MR_SERIALBITS=1,
      MR_PARALLELPORT=2,
      MR_PARALLELBITS=3,
      MR_ALLOCMISCRESOURCE=-6,
      MR_FREEMISCRESOURCE=-$c

#define MISCNAME 'misc.resource'
