OPT MODULE
OPT EXPORT

MODULE 'utility/tagitem'

CONST LED_DUMMY=TAG_USER+$04000000

CONST LED_PAIRS=LED_DUMMY+1,
      LED_VALUES=LED_DUMMY+2,
      LED_COLON=LED_DUMMY+3,
      LED_NEGATIVE=LED_DUMMY+4,
      LED_SIGNED=LED_DUMMY+5
