OPT MODULE
OPT EXPORT

MODULE 'utility/tagitem'

CONST BUTTON_DUMMY=TAG_USER+$4000000

CONST BUTTON_PUSHBUTTON=BUTTON_DUMMY+1,
      BUTTON_GLYPH=BUTTON_DUMMY+2,
      BUTTON_ARRAY=BUTTON_DUMMY+3,
      BUTTON_TEXTPEN=BUTTON_DUMMY+5,
      BUTTON_FILLPEN=BUTTON_DUMMY+6,
      BUTTON_FILLTEXTPEN=BUTTON_DUMMY+7,
      BUTTON_BACKGROUNDPEN=BUTTON_DUMMY+8,
      BUTTON_CURRENT=BUTTON_DUMMY+9
