OPT MODULE
OPT EXPORT

MODULE 'utility/tagitem'

ENUM TL_TEXTPEN, TL_BACKGROUNDPEN, TL_FILLTEXTPEN, TL_FILLPEN, MAX_TL_PENS

OBJECT tablabel
  label:PTR TO CHAR
  pen1:INT, pen2:INT, pen3:INT, pen4:INT
  attrs:PTR TO tagitem
ENDOBJECT

CONST TABS_DUMMY=TAG_USER+$4000000

CONST TABS_LABELS=TABS_DUMMY+1,
      TABS_CURRENT=TABS_DUMMY+2