  OPT MODULE
  OPT EXPORT
  OPT PREPROCESS

  MODULE 'utility/tagitem'

ENUM TL_TEXTPEN, TL_BACKGROUNDPEN, TL_FILLTEXTPEN, TL_FILLPEN, MAX_TL_PENS

OBJECT tablabel
  label:PTR TO CHAR
  pens[4]:ARRAY OF INT
  attrs:PTR TO tagitem
ENDOBJECT     /* SIZEOF=16 */

CONST TABS_DUMMY=$84000000,
      TABS_LABELS=$84000001,
      TABS_CURRENT=$84000002
      

