OPT MODULE
OPT EXPORT

CONST UTILITY_NAME_I=1

OBJECT namedobject
  object:LONG
ENDOBJECT     /* SIZEOF=NONE !!! */

CONST ANO_NAMESPACE=$FA0,
      ANO_USERSPACE=$FA1,
      ANO_PRIORITY=$FA2,
      ANO_FLAGS=$FA3,
      NSB_NODUPS=0,
      NSB_CASE=1,
      NSF_NODUPS=1,
      NSF_CASE=2

