OPT MODULE
OPT EXPORT

OBJECT tagitem
  tag:LONG
  data:LONG
ENDOBJECT     /* SIZEOF=8 */

CONST TAG_DONE=0,
      TAG_END=0,
      TAG_IGNORE=1,
      TAG_MORE=2,
      TAG_SKIP=3,
      TAG_USER=$80000000,
      TAGFILTER_AND=0,
      TAGFILTER_NOT=1,
      MAP_REMOVE_NOT_FOUND=0,
      MAP_KEEP_NOT_FOUND=1
