  OPT MODULE
  OPT EXPORT
  OPT PREPROCESS

CONST IOERR_OPENFAIL=-1,
      IOERR_ABORTED=-2,
      IOERR_NOCMD=-3,
      IOERR_BADLENGTH=-4,
      IOERR_BADADDRESS=-5,
      IOERR_UNITBUSY=-6,
      IOERR_SELFTEST=-7,
      ERR_OPENDEVICE=-1

