  OPT MODULE
  OPT EXPORT
  OPT PREPROCESS
  
OBJECT bb
  id[4]:ARRAY OF CHAR
  chksum:LONG
  dosblock:LONG
ENDOBJECT     /* SIZEOF=12 */

CONST BOOTSECTS=2,
      BBNAME_DOS=$444F5300,
      BBNAME_KICK=$4B49434B
