OPT MODULE
OPT EXPORT

CONST IND_ADDHANDLER=9,
      IND_REMHANDLER=10,
      IND_WRITEEVENT=11,
      IND_SETTHRESH=12,
      IND_SETPERIOD=13,
      IND_SETMPORT=14,
      IND_SETMTYPE=15,
      IND_SETMTRIG=16

