name: Makefile CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: dmcoles/amiga-evo-cicd
      credentials:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
    steps: 
      - uses: actions/checkout@v4
      - name: run build
        run: |
           vamos -c /usr/amiga/.vamosrc -H disable -m 20000 --cwd esource: -V system:/usr/amiga -V esource:$GITHUB_WORKSPACE make EVO
      - name: add build artifacts to publish
        run: |
          mkdir output
          cp $GITHUB_WORKSPACE/EVO output
          cd output
          lha a ../evo-dev${{ github.sha }}.lha *
      - name: Update release title
        uses: mini-bomba/create-github-release@v1.1.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: dev-build
          name: automated dev build ${{ github.event.repository.pushed_at}}
          files: evo-dev${{ github.sha }}.lha
